let a = 5;
let b = 3;
let sum = a + b;
let difference = a - b;
let product = a * b;
let quotient = a / b;
let remainder = a % b;
console.log("Sum:", sum);
console.log("Difference:", difference);
console.log("Product:", product);
console.log("Quotient:", quotient);
console.log("Remainder:", remainder);
let angle = 45; 
let radians = angle * (Math.PI / 180);
let sineValue = Math.sin(radians);
let power = Math.pow(2, 3);
let squareRoot = Math.sqrt(16);
console.log("Sin:",Math.sin(a));
console.log("Cos:",Math.cos(b));
console.log("Max:",Math.max(a, b));
console.log("Square:",Math.sqrt(a * b));
console.log("Sine of 45 degrees:", sineValue);
console.log("2^3:", power);
console.log("Square root of 16:", squareRoot);
